from time import sleep
print("# bem vindo ao banco #")
def space():
	print("#"*30)
space()
print("Faça Seu cadastro")
space()
nome=input('qual seu Nome ?\n')
print('Ola {} Bem vindo Ao melho banco '.format(nome))
space()
print('Cadastre uma Senha')
space()
senha=input("escolha uma Senha\n")

print("Casdastrando aguarde..")
sleep(5)
print("70%..")
sleep(6)
print("90%...")
sleep(7)
print("100....")
sleep(5)
space()
print("Bem vindo Ao banco")
space()
print("Desfrute dos Nossos produtos avontade")